## Pair Programming Python + SQL

1. Importar las librerías necesarias para crear la conexión y trbajar con Pandas.

In [1]:
!pip install mysql-connector

!pip install mysql-connector-python

Requirement already satisfied: mysql-connector in /home/admin_diana/anaconda3/lib/python3.9/site-packages (2.2.9)
Requirement already satisfied: mysql-connector-python in /home/admin_diana/anaconda3/lib/python3.9/site-packages (8.4.0)

In [14]:
import mysql.connector
from mysql.connector import errorcode

import pandas as pd
import numpy as np

2. Crear la conexión a la base de datos Northwind que devuelva un mensaje de error si algo no ocurre cómo debería.

In [3]:
try:
    conexion = mysql.connector.connect(
        user = 'root',
        host = '127.0.0.1', 
        password = 'AlumnaAdalab',
        database = 'northwind'
    )
    print("Conexión establecida correctamente.")
    
except mysql.connector.Error as err:
  if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
    print("Algo fue mal con tu user name o password")
  elif err.errno == errorcode.ER_BAD_DB_ERROR:
    print("La database no existe")
  else:
    print(err)

Conexión establecida correctamente.

3. Usando "information_schema", extraer los nombres de las columnas de la tabla "customers" de la BBDD "northwind".

In [6]:
conexion = mysql.connector.connect(
        user = 'root',
        host = '127.0.0.1', 
        password = 'AlumnaAdalab',
        database = 'information_schema'
    )

mycursor = conexion.cursor()

mycursor.execute("SELECT column_name FROM columns WHERE table_name = 'customers' and table_schema = 'northwind'")

resultados = mycursor.fetchall()

resultados

[('CustomerID',),
 ('CompanyName',),
 ('ContactName',),
 ('ContactTitle',),
 ('Address',),
 ('City',),
 ('Region',),
 ('PostalCode',),
 ('Country',),
 ('Phone',),
 ('Fax',)]

4. Seleccionar todo de la tabla "customers" donde "country" sea "USA" o "Germany". Almacenar los resultados en una variable.

In [12]:
conexion = mysql.connector.connect(
        user = 'root',
        host = '127.0.0.1', 
        password = 'AlumnaAdalab',
        database = 'northwind'
    )

mycursor = conexion.cursor()

mycursor.execute("SELECT * FROM customers WHERE country IN ('USA', 'Germany')")

resultados = mycursor.fetchall()

resultados

[('ALFKI',
  'Alfreds Futterkiste',
  'Maria Anders',
  'Sales Representative',
  'Obere Str. 57',
  'Berlin',
  None,
  '12209',
  'Germany',
  '030-0074321',
  '030-0076545'),
 ('BLAUS',
  'Blauer See Delikatessen',
  'Hanna Moos',
  'Sales Representative',
  'Forsterstr. 57',
  'Mannheim',
  None,
  '68306',
  'Germany',
  '0621-08460',
  '0621-08924'),
 ('DRACD',
  'Drachenblut Delikatessen',
  'Sven Ottlieb',
  'Order Administrator',
  'Walserweg 21',
  'Aachen',
  None,
  '52066',
  'Germany',
  '0241-039123',
  '0241-059428'),
 ('FRANK',
  'Frankenversand',
  'Peter Franken',
  'Marketing Manager',
  'Berliner Platz 43',
  'Mnchen',
  None,
  '80805',
  'Germany',
  '089-0877310',
  '089-0877451'),
 ('GREAL',
  'Great Lakes Food Market',
  'Howard Snyder',
  'Marketing Manager',
  '2732 Baker Blvd.',
  'Eugene',
  'OR',
  '97403',
  'USA',
  '(503) 555-7555',
  None),
 ('HUNGC',
  'Hungry Coyote Import Store',
  'Yoshi Latimer',
  'Sales Representative',
  'City Center Plaza 516 Main St.',
  'Elgin',
  'OR',
  '97827',
  'USA',
  '(503) 555-6874',
  '(503) 555-2376'),
 ('KOENE',
  'Kniglich Essen',
  'Philip Cramer',
  'Sales Associate',
  'Maubelstr. 90',
  'Brandenburg',
  None,
  '14776',
  'Germany',
  '0555-09876',
  None),
 ('LAZYK',
  'Lazy K Kountry Store',
  'John Steel',
  'Marketing Manager',
  '12 Orchestra Terrace',
  'Walla Walla',
  'WA',
  '99362',
  'USA',
  '(509) 555-7969',
  '(509) 555-6221'),
 ('LEHMS',
  'Lehmanns Marktstand',
  'Renate Messner',
  'Sales Representative',
  'Magazinweg 7',
  'Frankfurt a.M.',
  None,
  '60528',
  'Germany',
  '069-0245984',
  '069-0245874'),
 ('LETSS',
  "Let's Stop N Shop",
  'Jaime Yorres',
  'Owner',
  '87 Polk St. Suite 5',
  'San Francisco',
  'CA',
  '94117',
  'USA',
  '(415) 555-5938',
  None),
 ('LONEP',
  'Lonesome Pine Restaurant',
  'Fran Wilson',
  'Sales Manager',
  '89 Chiaroscuro Rd.',
  'Portland',
  'OR',
  '97219',
  'USA',
  '(503) 555-9573',
  '(503) 555-9646'),
 ('MORGK',
  'Morgenstern Gesundkost',
  'Alexander Feuer',
  'Marketing Assistant',
  'Heerstr. 22',
  'Leipzig',
  None,
  '04179',
  'Germany',
  '0342-023176',
  None),
 ('OLDWO',
  'Old World Delicatessen',
  'Rene Phillips',
  'Sales Representative',
  '2743 Bering St.',
  'Anchorage',
  'AK',
  '99508',
  'USA',
  '(907) 555-7584',
  '(907) 555-2880'),
 ('OTTIK',
  'Ottilies Kseladen',
  'Henriette Pfalzheim',
  'Owner',
  'Mehrheimerstr. 369',
  'Kln',
  None,
  '50739',
  'Germany',
  '0221-0644327',
  '0221-0765721'),
 ('QUICK',
  'QUICK-Stop',
  'Horst Kloss',
  'Accounting Manager',
  'Taucherstrae 10',
  'Cunewalde',
  None,
  '01307',
  'Germany',
  '0372-035188',
  None),
 ('RATTC',
  'Rattlesnake Canyon Grocery',
  'Paula Wilson',
  'Assistant Sales Representative',
  '2817 Milton Dr.',
  'Albuquerque',
  'NM',
  '87110',
  'USA',
  '(505) 555-5939',
  '(505) 555-3620'),
 ('SAVEA',
  'Save-a-lot Markets',
  'Jose Pavarotti',
  'Sales Representative',
  '187 Suffolk Ln.',
  'Boise',
  'ID',
  '83720',
  'USA',
  '(208) 555-8097',
  None),
 ('SPLIR',
  'Split Rail Beer & Ale',
  'Art Braunschweiger',
  'Sales Manager',
  'P.O. Box 555',
  'Lander',
  'WY',
  '82520',
  'USA',
  '(307) 555-4680',
  '(307) 555-6525'),
 ('THEBI',
  'The Big Cheese',
  'Liz Nixon',
  'Marketing Manager',
  '89 Jefferson Way Suite 2',
  'Portland',
  'OR',
  '97201',
  'USA',
  '(503) 555-3612',
  None),
 ('THECR',
  'The Cracker Box',
  'Liu Wong',
  'Marketing Assistant',
  '55 Grizzly Peak Rd.',
  'Butte',
  'MT',
  '59801',
  'USA',
  '(406) 555-5834',
  '(406) 555-8083'),
 ('TOMSP',
  'Toms Spezialitten',
  'Karin Josephs',
  'Marketing Manager',
  'Luisenstr. 48',
  'Mnster',
  None,
  '44087',
  'Germany',
  '0251-031259',
  '0251-035695'),
 ('TRAIH',
  "Trail's Head Gourmet Provisioners",
  'Helvetius Nagy',
  'Sales Associate',
  '722 DaVinci Blvd.',
  'Kirkland',
  'WA',
  '98034',
  'USA',
  '(206) 555-8257',
  '(206) 555-2174'),
 ('WANDK',
  'Die Wandernde Kuh',
  'Rita Mller',
  'Sales Representative',
  'Adenauerallee 900',
  'Stuttgart',
  None,
  '70563',
  'Germany',
  '0711-020361',
  '0711-035428'),
 ('WHITC',
  'White Clover Markets',
  'Karl Jablonski',
  'Owner',
  '305 - 14th Ave. S. Suite 3B',
  'Seattle',
  'WA',
  '98128',
  'USA',
  '(206) 555-4112',
  '(206) 555-4115')]

5. Convertir los resultados del ejercicio anterior en un Dataframe (no od olvidéis de poner el nombre a las columnas en el orden correcto).

In [25]:
nombre_columnas = ["CustomerID", "CompanyName", "ContactName", "ContactTitle", "Address", "City", "Region", "PostalCode", "Country", "Phone", "Fax"]

df = pd.DataFrame(resultados, columns = nombre_columnas)

df

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,None,12209,Germany,030-0074321,030-0076545
1,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,None,68306,Germany,0621-08460,0621-08924
2,DRACD,Drachenblut Delikatessen,Sven Ottlieb,Order Administrator,Walserweg 21,Aachen,None,52066,Germany,0241-039123,0241-059428
3,FRANK,Frankenversand,Peter Franken,Marketing Manager,Berliner Platz 43,Mnchen,None,80805,Germany,089-0877310,089-0877451
4,GREAL,Great Lakes Food Market,Howard Snyder,Marketing Manager,2732 Baker Blvd.,Eugene,OR,97403,USA,(503) 555-7555,None
5,HUNGC,Hungry Coyote Import Store,Yoshi Latimer,Sales Representative,City Center Plaza 516 Main St.,Elgin,OR,97827,USA,(503) 555-6874,(503) 555-2376
6,KOENE,Kniglich Essen,Philip Cramer,Sales Associate,Maubelstr. 90,Brandenburg,None,14776,Germany,0555-09876,None
7,LAZYK,Lazy K Kountry Store,John Steel,Marketing Manager,12 Orchestra Terrace,Walla Walla,WA,99362,USA,(509) 555-7969,(509) 555-6221
8,LEHMS,Lehmanns Marktstand,Renate Messner,Sales Representative,Magazinweg 7,Frankfurt a.M.,None,60528,Germany,069-0245984,069-0245874
9,LETSS,Let's Stop N Shop,Jaime Yorres,Owner,87 Polk St. Suite 5,San Francisco,CA,94117,USA,(415) 555-5938,None
10,LONEP,Lonesome Pine Restaurant,Fran Wilson,Sales Manager,89 Chiaroscuro Rd.,Portland,OR,97219,USA,(503) 555-9573,(503) 555-9646
11,MORGK,Morgenstern Gesundkost,Alexander Feuer,Marketing Assistant,Heerstr. 22,Leipzig,None,04179,Germany,0342-023176,None
12,OLDWO,Old World Delicatessen,Rene Phillips,Sales Representative,2743 Bering St.,Anchorage,AK,99508,USA,(907) 555-7584,(907) 555-2880
13,OTTIK,Ottilies Kseladen,Henriette Pfalzheim,Owner,Mehrheimerstr. 369,Kln,None,50739,Germany,0221-0644327,0221-0765721
14,QUICK,QUICK-Stop,Horst Kloss,Accounting Manager,Taucherstrae 10,Cunewalde,None,01307,Germany,0372-035188,None
15,RATTC,Rattlesnake Canyon Grocery,Paula Wilson,Assistant Sales Representative,2817 Milton Dr.,Albuquerque,NM,87110,USA,(505) 555-5939,(505) 555-3620
16,SAVEA,Save-a-lot Markets,Jose Pavarotti,Sales Representative,187 Suffolk Ln.,Boise,ID,83720,USA,(208) 555-8097,None
17,SPLIR,Split Rail Beer & Ale,Art Braunschweiger,Sales Manager,P.O. Box 555,Lander,WY,82520,USA,(307) 555-4680,(307) 555-6525
18,THEBI,The Big Cheese,Liz Nixon,Marketing Manager,89 Jefferson Way Suite 2,Portland,OR,97201,USA,(503) 555-3612,None
19,THECR,The Cracker Box,Liu Wong,Marketing Assistant,55 Grizzly Peak Rd.,Butte,MT,59801,USA,(406) 555-5834,(406) 555-8083
20,TOMSP,Toms Spezialitten,Karin Josephs,Marketing Manager,Luisenstr. 48,Mnster,None,44087,Germany,0251-031259,0251-035695
21,TRAIH,Trail's Head Gourmet Provisioners,Helvetius Nagy,Sales Associate,722 DaVinci Blvd.,Kirkland,WA,98034,USA,(206) 555-8257,(206) 555-2174
22,WANDK,Die Wandernde Kuh,Rita Mller,Sales Representative,Adenauerallee 900,Stuttgart,None,70563,Germany,0711-020361,0711-035428
23,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115

6. Muestrar las 10 primeras filas del Dataframe y las 10 últimas.

In [26]:
df.head(10)

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,None,12209,Germany,030-0074321,030-0076545
1,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,None,68306,Germany,0621-08460,0621-08924
2,DRACD,Drachenblut Delikatessen,Sven Ottlieb,Order Administrator,Walserweg 21,Aachen,None,52066,Germany,0241-039123,0241-059428
3,FRANK,Frankenversand,Peter Franken,Marketing Manager,Berliner Platz 43,Mnchen,None,80805,Germany,089-0877310,089-0877451
4,GREAL,Great Lakes Food Market,Howard Snyder,Marketing Manager,2732 Baker Blvd.,Eugene,OR,97403,USA,(503) 555-7555,None
5,HUNGC,Hungry Coyote Import Store,Yoshi Latimer,Sales Representative,City Center Plaza 516 Main St.,Elgin,OR,97827,USA,(503) 555-6874,(503) 555-2376
6,KOENE,Kniglich Essen,Philip Cramer,Sales Associate,Maubelstr. 90,Brandenburg,None,14776,Germany,0555-09876,None
7,LAZYK,Lazy K Kountry Store,John Steel,Marketing Manager,12 Orchestra Terrace,Walla Walla,WA,99362,USA,(509) 555-7969,(509) 555-6221
8,LEHMS,Lehmanns Marktstand,Renate Messner,Sales Representative,Magazinweg 7,Frankfurt a.M.,None,60528,Germany,069-0245984,069-0245874
9,LETSS,Let's Stop N Shop,Jaime Yorres,Owner,87 Polk St. Suite 5,San Francisco,CA,94117,USA,(415) 555-5938,None

In [27]:
df.tail(10)

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
14,QUICK,QUICK-Stop,Horst Kloss,Accounting Manager,Taucherstrae 10,Cunewalde,None,01307,Germany,0372-035188,None
15,RATTC,Rattlesnake Canyon Grocery,Paula Wilson,Assistant Sales Representative,2817 Milton Dr.,Albuquerque,NM,87110,USA,(505) 555-5939,(505) 555-3620
16,SAVEA,Save-a-lot Markets,Jose Pavarotti,Sales Representative,187 Suffolk Ln.,Boise,ID,83720,USA,(208) 555-8097,None
17,SPLIR,Split Rail Beer & Ale,Art Braunschweiger,Sales Manager,P.O. Box 555,Lander,WY,82520,USA,(307) 555-4680,(307) 555-6525
18,THEBI,The Big Cheese,Liz Nixon,Marketing Manager,89 Jefferson Way Suite 2,Portland,OR,97201,USA,(503) 555-3612,None
19,THECR,The Cracker Box,Liu Wong,Marketing Assistant,55 Grizzly Peak Rd.,Butte,MT,59801,USA,(406) 555-5834,(406) 555-8083
20,TOMSP,Toms Spezialitten,Karin Josephs,Marketing Manager,Luisenstr. 48,Mnster,None,44087,Germany,0251-031259,0251-035695
21,TRAIH,Trail's Head Gourmet Provisioners,Helvetius Nagy,Sales Associate,722 DaVinci Blvd.,Kirkland,WA,98034,USA,(206) 555-8257,(206) 555-2174
22,WANDK,Die Wandernde Kuh,Rita Mller,Sales Representative,Adenauerallee 900,Stuttgart,None,70563,Germany,0711-020361,0711-035428
23,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115

7. Mostrar 5 filas aleatorias del Dataframe.

In [28]:
df.sample(5)

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
4,GREAL,Great Lakes Food Market,Howard Snyder,Marketing Manager,2732 Baker Blvd.,Eugene,OR,97403,USA,(503) 555-7555,None
21,TRAIH,Trail's Head Gourmet Provisioners,Helvetius Nagy,Sales Associate,722 DaVinci Blvd.,Kirkland,WA,98034,USA,(206) 555-8257,(206) 555-2174
17,SPLIR,Split Rail Beer & Ale,Art Braunschweiger,Sales Manager,P.O. Box 555,Lander,WY,82520,USA,(307) 555-4680,(307) 555-6525
2,DRACD,Drachenblut Delikatessen,Sven Ottlieb,Order Administrator,Walserweg 21,Aachen,None,52066,Germany,0241-039123,0241-059428
16,SAVEA,Save-a-lot Markets,Jose Pavarotti,Sales Representative,187 Suffolk Ln.,Boise,ID,83720,USA,(208) 555-8097,None

8. ¿Hay nulos en el Dataframe? El resultado debe verse para cada una de las columnas.

In [30]:
df.isna()

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,True,False,False,False,True
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,True
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,True,False,False,False,True
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,True,False,False,False,False
14,False,False,False,False,False,False,True,False,False,False,True
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,True
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,True
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,True,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,True,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False

In [31]:
df.isnull().sum()

CustomerID       0
CompanyName      0
ContactName      0
ContactTitle     0
Address          0
City             0
Region          11
PostalCode       0
Country          0
Phone            0
Fax              7
dtype: int64

9. Mostrar los principales estadísticos.

In [34]:
df.describe(include = "object")

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
count,24,24,24,24,24,24,13,24,24,24,17
unique,24,24,24,9,24,23,8,24,2,24,17
top,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Portland,OR,12209,USA,030-0074321,030-0076545
freq,1,1,1,7,1,2,4,1,13,1,1

10. Mostrar el nombre de las columnas del Dataframe.

In [36]:
df.columns

Index(['CustomerID', 'CompanyName', 'ContactName', 'ContactTitle', 'Address',
       'City', 'Region', 'PostalCode', 'Country', 'Phone', 'Fax'],
      dtype='object')